version: "3.7"
services:
  caddy:
    image: caddy:2.2.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $HOME/docker/volumes/caddy:/data

  database:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    expose:
      - "8080"
